version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - $PGPORT:$PGPORT
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    env_file:
      - .env
